# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MARLDynamics',
                'doc_host': 'https://wbarfuss.github.io',
                'git_url': 'https://github.com/wbarfuss/MARLDynamics',
                'lib_path': 'MARLDynamics'},
  'syms': {'MARLDynamics.core': {'MARLDynamics.core.foo': ('core.html#foo', 'MARLDynamics/core.py')}}}
